### ISSUE TITLE
[fabric] Reinforced Shulker Boxes support

### ISSUE THREAD

**Issue by Aton-Kish** [TheIllusiveC4/CuriousShulkerBoxes#11]
**Please describe the new feature or change.**

Could you please support my new mod, [Reinforced Shulker Box](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes)?

maven repo: https://raw.githubusercontent.com/Aton-Kish/mcmod/maven
maven artifact: atonkish.reinfshulker:reinforced-shulker-boxes:${reinforcedShulkerBoxesVersion}
(or cursemaven)

**Please describe why you want this feature.**

**Comment by Panderine** [comment]
This would be extremely useful !!

**Comment by MOOOOs** [comment]
im looking forward to this too

**Comment by meowisme** [comment]
Damn it's been a few years but this would _seriously_ be amazing

**Comment by Panderine** [comment]
Thank you!
