### ISSUE TITLE
[Fabric - 1.17.1] no texture shulker box bug

### ISSUE THREAD

**Issue by xg787** [TheIllusiveC4/CuriousShulkerBoxes#13]
Trinket Shulker Boxes: 2.0.0
Trinkets: 3.0.4
Fabric: 0.11.7 - 1.17.1
 Observed Behavior: no texture 
Expected Behavior: normal shulker box texture

Crash Log: no crash :)

![2021-10-08_23 53 57](https://user-images.githubusercontent.com/59268579/136643491-9e11e434-5424-4c21-89cb-01e97a76ef40.png)

**Comment by TheIllusiveC4** [comment]
Not sure what's happening here as I was never able to reproduce it, but I released an update that updated some dependencies so try the newest version and see if this is still an issue.
