### ISSUE TITLE
[Fabric 1.17.1 - Crash] Latest Cardinal Components (3.1.1) "attempted duplicate class GeneratedComponentContainer" when loading world with Shulker Box equipped

### ISSUE THREAD

**Issue by Desempregago** [TheIllusiveC4/CuriousShulkerBoxes#14]
#### Versions
* Trinket Shulker Boxes: 2.0.0-1.17
* Trinkets: 3.0.4
* Fabric: 0.12.1 + API 0.41.0-1.17

[Crash Report](https://pastebin.com/R2biXevc)

**Comment by Desempregago** [comment]
ah, forgot to mention: Cardinal Components API 3.1.1

**Comment by Desempregago** [comment]
also, for some reason, the crashes started after removing Sodium. I have NO idea why it would crash without Sodium.

**Comment by TheIllusiveC4** [comment]
I updated the CCA dependency in the latest version so test that out and see if this is still an issue.

**Comment by SpiderAang** [comment]
Same problem same infos
