### ISSUE TITLE
[1.18.2] Inmis prevents Shulker Box Trinket use

### ISSUE THREAD

**Issue by Lurrae** [TheIllusiveC4/CuriousShulkerBoxes#16]
#### Versions:
* Minecraft: 1.18.2
* Trinket Shulker Boxes: 2.0.1
* Trinkets: 3.3.0
* Fabric: 0.13.3
* Fabric API: 0.48.0
#### Observed Behavior:
When the mod Inmis is enabled, Shulker Boxes cannot be placed in the back Trinkets slot, and Shulker Boxes lose their tooltip detailing their ability to be placed in the back Trinkets slot. If a Shulker Box was already in the back Trinkets slot and Inmis is enabled after that, the Shulker Box functions as intended until it is removed from the back Trinket slot, at which point it cannot be placed back. This presumably happens with any mod that adds a back Trinkets item, but at the moment I have only tested Inmis. Disabling Inmis' config options for Trinkets compatibility does **not** fix the issue.
#### Expected Behavior:
Shulker Boxes should retain their ability to be placed in the back Trinkets slot even when other mods which add back Trinkets items are present.
#### Steps to Reproduce:
1. Enable Fabric API, Trinkets, and Trinket Shulker Boxes
2. Load up a new Creative world and obtain a Shulker Box
3. Observe that the Shulker Box is capable of being placed in the back Trinkets slot, and has a tooltip mentioning such
4. Save & exit the game with the Shulker Box in the back Trinkets slot, and enable Inmis
5. The Shulker Box remains in the back Trinkets slot as intended, and can be opened with the keybind, though it no longer has the tooltip stating it can be placed in the back Trinkets slot
6. Remove the Shulker Box from the back Trinkets slot, and observe that the Shulker Box can no longer be placed in the back Trinkets slot

(Note: I have also submitted a bug report to Inmis' github page, in case the bug is on their end)

**Comment by TheIllusiveC4** [comment]
I believe this is a bug with Trinkets itself. I'm preparing to make a PR that will address it on that end.
