### ISSUE TITLE
Sudden Exit World to Main Menu

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/CuriousShulkerBoxes#18]
#### Notice
Return Back to main menu when opening/equiping Shulker. Sometimes, not always.

#### Versions (Be specific, do not write "latest"):
* Trinket Shulker Boxes: 2.0.1
* Trinket : 3.3.1
* Fabric API : 0.54.0
* Fabric Loader : 0.14.6

#### Observed Behavior:
Game Exit on press hotkey to open shulker on trinket.

#### Expected Behavior:
Equiped Shulker Open Inventory

#### Steps to Reproduce:
1. Press hotkey open equiped shulker (sometimes equiping also crash)
.

Crash Log: 
https://pastebin.com/bvUM4pYy

**Comment by TheIllusiveC4** [comment]
Can you post the whole crash log? It seems like you only posted a small part of it.

**Comment by ardissaps** [comment]
> Can you post the whole crash log? It seems like you only posted a small part of it.

Ok, it happen pretty rare. I'll get more log later if happen again.

**Comment by ardissaps** [comment]
> Can you post the whole crash log? It seems like you only posted a small part of it.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/3/22, 9:55 PM
Description: Ticking entity

java.lang.IllegalStateException
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at dev.onyxstudios.cca.internal.base.GenericContainerBuilder.factoryNameSuffix(GenericContainerBuilder.java:70)
	at dev.onyxstudios.cca.api.v3.component.ComponentContainer$Factory$Builder.factoryNameSuffix(ComponentContainer.java:194)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.getFactoryClass(StaticItemComponentPlugin.java:84)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.createItemStackContainerFactory(StaticItemComponentPlugin.java:72)
	at net.minecraft.item.Item.cardinal_createComponents(Item:2068)
	at net.minecraft.item.ItemStack.getComponentContainer(ItemStack:4207)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.maybeGet(ComponentKey.java:109)
	at top.theillusivec4.trinketshulkerboxes.common.TrinketShulkerBox.tick(TrinketShulkerBox.java:31)
	at net.minecraft.entity.player.PlayerInventory.md762c2d$lambda$updateItems$0$1(PlayerInventory:5194)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362)
	at net.minecraft.entity.player.PlayerInventory.md762c2d$lambda$updateItems$1$0(PlayerInventory:5193)
	at java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.entity.player.PlayerInventory.handler$fcm001$updateItems(PlayerInventory:5192)
	at net.minecraft.entity.player.PlayerInventory.updateItems(PlayerInventory:260)
	at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity:557)
	at net.minecraft.client.network.ClientPlayerEntity.tickMovement(ClientPlayerEntity:836)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2354)
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:275)
	at net.minecraft.client.network.ClientPlayerEntity.tick(ClientPlayerEntity:212)
	at net.minecraft.client.world.ClientWorld.tickEntity(ClientWorld:217)
	at net.minecraft.world.World.tickEntity(World:485)
	at net.minecraft.client.world.ClientWorld.method_32124(ClientWorld:200)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:196)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1761)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at dev.onyxstudios.cca.internal.base.GenericContainerBuilder.factoryNameSuffix(GenericContainerBuilder.java:70)
	at dev.onyxstudios.cca.api.v3.component.ComponentContainer$Factory$Builder.factoryNameSuffix(ComponentContainer.java:194)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.getFactoryClass(StaticItemComponentPlugin.java:84)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.createItemStackContainerFactory(StaticItemComponentPlugin.java:72)
	at net.minecraft.class_1792.cardinal_createComponents(class_1792.java:2068)
	at net.minecraft.class_1799.getComponentContainer(class_1799.java:4207)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.maybeGet(ComponentKey.java:109)
	at top.theillusivec4.trinketshulkerboxes.common.TrinketShulkerBox.tick(TrinketShulkerBox.java:31)
	at net.minecraft.class_1661.md762c2d$lambda$updateItems$0$1(class_1661.java:5194)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362)
	at net.minecraft.class_1661.md762c2d$lambda$updateItems$1$0(class_1661.java:5193)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1661.handler$fcm001$updateItems(class_1661.java:5192)
	at net.minecraft.class_1661.method_7381(class_1661.java:260)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_746.method_6007(class_746.java:836)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 2
	Entity Name: ardissaps
	Entity's Exact location: 153.83, 89.00, -85.45
	Entity's Block location: World: (153,89,-86), Section: (at 9,9,10 in 9,5,-6; chunk contains blocks 144,0,-96 to 159,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['ardissaps'/2, l='ClientLevel', x=153.83, y=89.00, z=-85.45]]
	Chunk stats: 1024, 715
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,64,32), Section: (at 0,0,0 in 0,4,2; chunk contains blocks 0,0,32 to 15,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 52173 game time, 52173 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, continuity/default, continuity/glass_pane_culling_fix, Stay_True_1.18.zip, Terralith_2.2.x_Biome_Name_Fix.zip, Incendium_5.x_Biome_Name_Fix.zip, §6[ETF] Default.zip, unique-spawn-eggs-v1-3-1-18.zip, xali's Potions v1.0.zip, Enchanted Books v0.5.zip, Xaero's Minimap - Mod Icons.zip, Unity-1.18.X-Dark-0.8.1.zip, Fabric Mods, Jaden's Nether Expansion_1.18.2.zip, Better-Leaves-7.0-1.13+.zip, DARK EmbellishedStone.zip, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3586659048 bytes (3420 MiB) / 6308233216 bytes (6016 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x17c8
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 26062.05
	Virtual memory used (MB): 21448.64
	Swap memory total (MB): 9727.80
	Swap memory used (MB): 437.43
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx6144M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		additionalstructures: Additional Structures 3.0.3
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		advancementplaques: Advancement Plaques 1.4.4
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		amecs: Amecs 1.3.7+mc.1.18.2
			amecsapi: Amecs API 1.3.5+mc22w06a
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		animatica: Animatica 0.4+1.18
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.4.68
		attributefix: AttributeFix 14.0.2
		autorun: AutoRun 0.4.0
		autotag: AutoTag 1.1.0
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 1.4.7
		better_runtime_resource_pack: Better Runtime Resource Pack 0.6.2
			advanced_runtime_resource_pack: Advanced Runtime Resource Pack 0.6.2
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterf3: BetterF3 1.2.5
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.3
		betternether: Better Nether 6.1.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.7.3
		blanket-client-tweaks: Blanket Client-tweaks 1.0.3
		boathud: BoatHud 1.1.0
		bookshelf: Bookshelf 13.1.17
		brb: Better Recipe Book 1.5.6
		byg: Oh The Biomes You'll Go 1.4
		campanion: Campanion 3.0.4
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		cem: Custom Entity Models 0.7.1
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chime: Chime 1.2.1
		citresewn: CIT Resewn 1.0.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-api: Cloth API 3.2.64
			cloth-basic-math: cloth-basic-math 0.6.0
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+8
		collective-fabric: Collective (Fabric) 4.26
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.1+mc.1.18.2
		command_structures: Command Structures 2.0.1+1.18.2
		completeconfig: CompleteConfig 1.4.1
		continuity: Continuity 1.1.0+1.18.2
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.6.11
		creeperoverhaul: Creeper Overhaul 1.3.1
		cullleaves: Cull Leaves 2.3.2
		debugify: Debugify 1.11.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		dimores: DimensionalOres 1.0.2
		draggable-resource-packs: Draggable Resource Packs 2.0.0
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easyshulkerboxes: Easy Shulker Boxes 3.1.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchdesc: EnchantmentDescriptions 10.0.3
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		entity_texture_features: Entity Texture Features 3.0.4
		entityculling: EntityCulling-Fabric 1.5.1
		expandeddelight: Expanded Delight 0.1.7
		extrasounds: Extra Sounds 2.2.1+1.18.2
			soundcategories: Sound Categories 1.2.1+1.18
		fabric: Fabric API 0.54.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.6+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.2+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.6
		fabricskyboxes: FabricSkyBoxes 0.5.5
		fallingtree: FallingTree 3.5.1
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.1.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		fps: FPS Monitor 1.18-1.2.1-Fabric
		freecam: Freecam 1.0.6
		friendsandfoes: Friends&Foes 1.4.2
		fvt: Flour's Various Tweaks 1.10.0-mc1.18.2
		gammautils: Gamma Utils 1.5.7
		geckolib3: Geckolib 3.0.42
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		global-datapack: Global Datapack 1.0
		goodall: Goodall 1.0.2
		graveyard: The Graveyard 1.8
			omega-config: OmegaConfig 1.2.2-1.18.1
		icarus: Icarus 1.11
		iceberg: Iceberg 1.0.38
		immersive_armors: Immersive Armors 1.3.4
		incendium: Incendium + Seed Fix 5.0.3
		indium: Indium 1.0.3+mc1.18.2
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.0
		iris: Iris 1.2.4-build.38
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		keymap: KeyMap 0.4.2-beta.3+1.18.1-fabric
			org_yaml_snakeyaml: snakeyaml 1.30
		ksyxis: Ksyxis 1.1
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		llamarama: Llamarama 1.7.0
		loadingscreentips: Loading Tips 1.0.1
		malilib: MaLiLib 0.12.1
		mca: Minecraft Comes Alive 7.3.0
		mcpppp: MCPPPP 0.7.1
		megane: megane 7.5.1
			megane-api: megane-api 7.1.0
			megane-fabric-transfer: megane-fabric-transfer 7.1.0
			megane-runtime: megane-runtime 7.2.0
			megane-vanilla: megane-vanilla 7.1.1
		memoryleakfix: memory Leak Fix 1.18.2-0.3.4
		minecraft: Minecraft 1.18.2
		moderate-loading-screen: Mod-erate Loading Screen 1.1.3
		modmenu: Mod Menu 3.2.2
		modsettings: ModSettings 1.1.0+1.18.1
		moreculling: More Culling 1.18.2-0.1.0
		moremcmeta: MoreMcmeta 1.18.2-3.0.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mythicmounts: Mythic Mounts 1.18.2-7.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.18.2
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		paperdoll: PaperDoll 1.1.0-mc1.18
		patchouli: Patchouli 1.18.2-69-FABRIC
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		prefab: Prefab 3.1.5
		presencefootsteps: Presence Footsteps 1.5.0
			kirin: Kirin UI 1.10.0
		puzzle: Puzzle 1.2.1
			midnightlib: MidnightLib 0.4.0
			puzzle-base: Puzzle Base 1.2.1
			puzzle-gui: Puzzle GUI 1.2.1
			puzzle-models: Puzzle Models 1.2.1
			puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		puzzleslib: Puzzles Lib 3.3.5
		reasonable-sorting: Reasonable Sorting 1.5
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		repurposed_structures: Repurposed Structures 4.1.12+1.18.2
		respackopts: Resource Pack Options 2.10.2
			com_github_meteordevelopment_starscript: starscript 0.1.9
			libjf-base: LibJF Base 2.8.1
			libjf-data-manipulation-v0: LibJF Data Manipulation 2.8.1
			libjf-unsafe-v0: LibJF Unsafe 2.8.1
		roughlyenoughitems: Roughly Enough Items 8.2.470
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		seedfix: Seed Fix 1.0.1
		showmeyourskin: Show Me Your Skin! 1.1.2+1.18.2
		shwfox: Shadew's Foxes 1.3+fabric
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		spoornweaponattributes: SpoornWeaponAttributes 3.4
			net_objecthunter_exp4j: exp4j 0.4.8
		stoneholm: Stoneholm 1.4.3
		suggestion_tweaker: Suggestion Tweaker 1.18.2-1.2.0
		t_and_t: Towns and Towers - Structure Add-on 1.6
		terrablender: TerraBlender 1.1.0.101
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		tputils: TP Utils 1.5.12
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.1
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		tweakermore: TweakerMore 3.3.0
			conditional-mixin: conditional mixin 0.3.0
		vanityslots: Vanity Slots 1.1.2
		villager-hats: Villager Hats 1.4.0
		waystones: Waystones 2.5.3
		weaponmaster: YDM's Weapon Master 1-18-x
		whats_that_slot: What's That Slot? 1.2.3+1.18.1
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		wthit: wthit 4.10.3
		wthit-plugins: Wthit Plugins 1.0.5
		xaerominimap: Xaero's Minimap 22.9.0
		xaeroworldmap: Xaero's World Map 1.23.1
		xtraarrows: Xtra Arrows 1.8.3
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
		zoomify: Zoomify 1.6.0
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: ComplementaryShaders_v4.4.zip
		Profile: Custom (+66 options changed by user)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, continuity/default, continuity/glass_pane_culling_fix, file/Stay_True_1.18.zip (incompatible), file/Terralith_2.2.x_Biome_Name_Fix.zip, file/Incendium_5.x_Biome_Name_Fix.zip, file/§6[ETF] Default.zip (incompatible), file/unique-spawn-eggs-v1-3-1-18.zip, file/xali's Potions v1.0.zip (incompatible), file/Enchanted Books v0.5.zip, file/Xaero's Minimap - Mod Icons.zip, file/Unity-1.18.X-Dark-0.8.1.zip, Fabric Mods, file/Jaden's Nether Expansion_1.18.2.zip (incompatible), file/Better-Leaves-7.0-1.13+.zip (incompatible), file/DARK EmbellishedStone.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['ardissaps'/2, l='ServerLevel[New World]', x=153.83, y=89.00, z=-85.45]]
	Data Packs: vanilla, file/BlazeandCave's Advancements Pack Terralith.zip (incompatible), file/BlazeandCaves Advancements Pack 1.13.8.zip, file/Forest_Village.zip, file/Repurposed_Structures-Better_Strongholds_v3.zip, file/Repurposed_Structures-Farmers_Delight_v3.zip (incompatible), file/Repurposed_Structures-Friends_And_Foes-v1.zip, file/Repurposed_Structures-More_Villagers_v6.zip, file/better-trees-1-5-1-cavesandcliffs.zip (incompatible), file/ichphilipp-s-endcity-better-end-1-18-1.zip (incompatible), file/morevillages2.zip (incompatible), Fabric Mods
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: None

**Comment by ardissaps** [comment]
CrashLog : 
https://pastebin.com/Hnzv5Lnp

Launcher Log :
https://paste.atlauncher.com/view/b135547a-30b3-41a0-804a-d464094c6b53

 @TheIllusiveC4

**Comment by ardissaps** [comment]
Not Enough Crash Log (Crash to Main Menu):
https://bytebin.lucko.me/qFfVkHL6q3

Launcher Log : 
https://paste.atlauncher.com/view/b6c25d0e-0b63-4459-a1c6-d463ed326754

Crashy :
https://crashy.net/6etJ9EeyoHCNBm42iqce

**Comment by ardissaps** [comment]
https://paste.atlauncher.com/view/b77ab300-f680-4a5e-b946-bc8fffb2b913
