### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/CuriousShulkerBoxes#19]
https://pastebin.com/YGEYUW5j

**Comment by ardissaps** [comment]
Would you please port the fix for 1.18.2 sir? thank you verymuch

**Comment by TheIllusiveC4** [comment]
It is for 1.18.2 already.

**Comment by ardissaps** [comment]
> It is for 1.18.2 already.

Ah yes, sorry! I am was blind.
