### ISSUE TITLE
[Request] Support for Reinforced Shulker Boxes

### ISSUE THREAD

**Issue by TprScruffy** [TheIllusiveC4/CuriousShulkerBoxes#21]
These two mods are perfect for cross compatibility. Maybe something to add for the next version. Love not having to stuff around with backpack mods anymore.

https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes

Thanks
Scruff

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/shulkerboxslot/issues/11
