### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by MOOOOs** [TheIllusiveC4/CuriousShulkerBoxes#22]
**Please describe the new feature or change.**
Please update this awesome mod to support MC 1.19.2

**Please describe why you want this feature.**
game has been updates i guess everyone be happy to use this on newer game

**Comment by TheIllusiveC4** [comment]
It's already updated to 1.19.2.

**Comment by MOOOOs** [comment]
Thanks didn't notice :D
