### ISSUE TITLE
Allow toggling shulker box visibility

### ISSUE THREAD

**Issue by poly2it** [TheIllusiveC4/CuriousShulkerBoxes#23]
I think the ability to toggle the visibility of an equipped shulker box through a config would enhance this mod. I personally prefer not to have it shown, as I think it bloats the player model. 

If this was to be implemented it would make sense to have it in a config file, so that modpack creators to disable it for all players playing in a modpack.

**Comment by TheIllusiveC4** [comment]
Is there a reason that the current per-player visibility toggle is not enough?

Edit: Ah actually, I forgot that Trinkets on Fabric does not have this feature and you could be referring to Fabric. Is that the case?

**Comment by poly2it** [comment]
> Is there a reason that the current per-player visibility toggle is not enough?
> 
> Edit: Ah actually, I forgot that Trinkets on Fabric does not have this feature and you could be referring to Fabric. Is that the case?

Yes, I am using the fabric version.
