### ISSUE TITLE
Adding a shulker box with NBT directly to the back slot doesn't 'initialize' it properly

### ISSUE THREAD

**Issue by vico93** [TheIllusiveC4/CuriousShulkerBoxes#3]
Well, the steps to reproduce it are the following:

1. Create a new singleplayer world as survival mode;
2. Give yourself a shulker box with the following command: `/give @s black_shulker_box{display:{Name:"{\"text\":\"BackPack\"}"},BlockEntityTag:{LootTable:"minecraft:chests/spawn_bonus_chest"}}`
3. **Don't open it yet**! Select the slot where the shulker box is and right-click it in the middle of the air;
4. The shulker box will be sent to the back slot without the "BackPack" custom name and empty
5. Now remove the shulker from back and place it on the ground. It now will get the "BackPack" name AND the random generated loot.

I'm using Forge 28.1.1, curios-FORGE-1.14.4-1.0 and curiousshulkerboxes-FORGE-1.14.4-1.0.

**Comment by TheIllusiveC4** [comment]
Although I am seeing that the loot isn't generated, I'm also seeing the custom name being initialized properly. Can you include a screenshot of what you're seeing on your end?

**Comment by vico93** [comment]
Yeah, when i give the shulker box it shows the custom name, but when i equip in the way described above it wont show the name in the GUI title when opened using the slot hotkey (ps.: game in portuguese brazil, so "Caixa de shulker" is the default name of Shulker Box in this language)
![2019-09-19_14 24 19](https://user-images.githubusercontent.com/3485505/65266436-74017b00-dae9-11e9-8cbd-38467f2664bd.png)

While after placing the shulker in the ground and opening after properly shows the block name in GUI title:
![2019-09-19_14 24 34](https://user-images.githubusercontent.com/3485505/65266504-95fafd80-dae9-11e9-9a4a-586fba688328.png)
