### ISSUE TITLE
[Feature]: 1.21(.1) update

### ISSUE THREAD

**Issue by vico93** [TheIllusiveC4/CuriousShulkerBoxes#37]
### What is the new feature or improvement?

Is there any chance we will see this mod updated again?

And if you don't have interest/can't update, can other mods do it via PR/forking?

**Comment by TheIllusiveC4** [comment]
I do plan on updating this to 1.21.x, I've just unfortunately been busy and have a huge backlog on my mods. I'm doing my best to get to this as soon as possible, but anyone who wants to speed things along can feel free to PR a 1.21.x port and I'll take a look at it.

**Comment by vico93** [comment]
Any updates? @TheIllusiveC4

**Comment by TheIllusiveC4** [comment]
Working on it now, hoping to target a batch of releases for 1.20.x and 1.21.x this weekend.

**Comment by TheIllusiveC4** [comment]
The updates were a little trickier than expected so apologies for the delay but I've finally released the 1.21.x port.
