### ISSUE TITLE
Enderite Mod Support

### ISSUE THREAD

**Issue by cntrik** [TheIllusiveC4/CuriousShulkerBoxes#6]
**Please describe the new feature or change.**
Allow for rendering of the [Enderite Shulker Box](https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric) on the players back

**Please describe why you want this feature.**
Would be a great addition to this narrow mod

**Comment by TheIllusiveC4** [comment]
Added in 1.1.1-1.16.5.
