### ISSUE TITLE
[1.17.1] Crash when equipping shulker box with latest Trinkets

### ISSUE THREAD

**Issue by Desempregago** [TheIllusiveC4/CuriousShulkerBoxes#9]
#### Versions:
* Trinket Shulker Boxes:  2.0.0 (1.17)
* Trinkets: 3.0.1
* Fabric: 0.11.6 with API 0.37
#### Steps to Reproduce:
1. Equip Shulker Box on Back Slot
2. ...
3. Crash

[Stacktrace](https://pastebin.com/zchza426) (Doesn't produce an actual crash log, it just closes the game).

**Comment by TheIllusiveC4** [comment]
I'm having a hard time reproducing this issue. Have you tried testing with only Trinkets and Trinket Shulker Boxes installed?

**Comment by Desempregago** [comment]
Forgot to close it :P

**Comment by SpiderAang** [comment]
Same problem with v1.17.1 mod v2.0.1 on fabric loader
